CREATE TABLE Kingdom (
    id_Kingdom NUMBER PRIMARY KEY,
    name_Kingdom VARCHAR2(255)
);

CREATE TABLE Phylum (
    id_Phylum NUMBER PRIMARY KEY,
    name_Phylum VARCHAR2(255),
    id_Kingdom NUMBER,
    FOREIGN KEY (id_Kingdom) REFERENCES Kingdom
);

CREATE TABLE Class (
    id_Class NUMBER PRIMARY KEY,
    name_Class VARCHAR2(255),
    id_Phylum NUMBER,
    FOREIGN KEY (id_Phylum) REFERENCES Phylum
);

CREATE TABLE Order_ (
    id_Order_ NUMBER PRIMARY KEY,
    name_Order_ VARCHAR2(255),
    id_Class NUMBER,
    FOREIGN KEY (id_Class) REFERENCES Class
);

CREATE TABLE Family (
    id_Family NUMBER PRIMARY KEY,
    name_Family VARCHAR2(255),
    id_Order_ NUMBER,
    FOREIGN KEY (id_Order_) REFERENCES Order_
);

CREATE TABLE Genus (
    id_Genus NUMBER PRIMARY KEY,
    name_Genus VARCHAR2(255),
    id_Family NUMBER,
    FOREIGN KEY (id_Family) REFERENCES Family
);

CREATE TABLE Species (
    id_Species NUMBER PRIMARY KEY,
    name_Species VARCHAR2(255),
    common_name VARCHAR2(255),
    id_Genus NUMBER,
    FOREIGN KEY (id_Genus) REFERENCES Genus
);

CREATE TABLE Location (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude NUMBER,
    longitude NUMBER
);

CREATE TABLE License (
    id_license NUMBER PRIMARY KEY,
    name VARCHAR2(200)
);

CREATE TABLE Country (
    id_country NUMBER PRIMARY KEY,
    name VARCHAR2(200)
);


CREATE TABLE Address (
    id_address NUMBER PRIMARY KEY,
    name VARCHAR2(200)
);


CREATE TABLE Mail (
    id_mail NUMBER PRIMARY KEY,
    name VARCHAR2(200)
);


CREATE TABLE User_ (
    id_user NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200),
    last_name VARCHAR2(200),
    last_name2 VARCHAR2(200),
    country NUMBER,
    address NUMBER,
    mail NUMBER,
    FOREIGN KEY (country) REFERENCES Country,
    FOREIGN KEY (address) REFERENCES Address,
    FOREIGN KEY (mail) REFERENCES Mail
);



CREATE TABLE Occurrence (

    id_Occurrence NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_Image NUMBER,
    autor NUMBER,
    date_ DATE,
    note VARCHAR2(1000),
    Kingdom VARCHAR2(200),
    Phylum VARCHAR2(200),
    Class VARCHAR2(200), 
    Order_ VARCHAR2(200),
    Family VARCHAR2(200),
    Genus VARCHAR2(200),
    Species VARCHAR2(200),
    common_name VARCHAR2(200),
    FOREIGN KEY (autor) REFERENCES User_,
    FOREIGN KEY (id_Image) REFERENCES Image

);


CREATE TABLE Image (
    id_Image NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR2(1000),
    license NUMBER,
    location NUMBER,
    owner NUMBER,
    FOREIGN KEY (license) REFERENCES License(id_license),
    FOREIGN KEY (location) REFERENCES Location(location_id),
    FOREIGN KEY (owner) REFERENCES User_
);
