-- language=PL/SQL

CREATE OR REPLACE FUNCTION getImage(id_Image IN NUMBER) RETURN VARCHAR2 IS
    url VARCHAR2(1000);
BEGIN
    SELECT url INTO url FROM Image I WHERE I.id_Image = id_Image;
    RETURN url;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
    WHEN OTHERS THEN
        RETURN NULL;
END;
/
