DELETE FROM Species;
ALTER TABLE Species AUTO_INCREMENT = 1;

DELETE FROM Genus;
ALTER TABLE Genus AUTO_INCREMENT = 1;

DELETE FROM Family;
ALTER TABLE Family AUTO_INCREMENT = 1;

DELETE FROM Order_;
ALTER TABLE Order_ AUTO_INCREMENT = 1;

DELETE FROM Class;
ALTER TABLE Class AUTO_INCREMENT = 1;

DELETE FROM Phylum;
ALTER TABLE Phylum AUTO_INCREMENT = 1;

DELETE FROM Kingdom;
ALTER TABLE Kingdom AUTO_INCREMENT = 1;
